---
# Bandit YAML configuration file

# Skip verification of SSL certificates (B501,B503)
# Skip importing subprocess module (B404)
# Skip hardcoded binding to all interfaces (B104)
skips:
  - B501  # Request with no certificate validation
  - B503  # SSL with bad defaults
  - B404  # Import of subprocess module
  - B104  # Binding to all interfaces (0.0.0.0)

# Exclude directories
exclude_dirs:
  - tests
  - venv
  - __pycache__

# Exclude specific files (if needed)
exclude_paths: []

# Severity level 
# We focus on high and medium severity issues
severity_level: medium

# Configuration for specific tests (if needed)
any_other_function_with_shell_equals_true:
  no_shell: [os.execl, os.execle, os.execlp, os.execlpe, os.execv, os.execve, os.execvp,
    os.execvpe, os.spawnl, os.spawnle, os.spawnlp, os.spawnlpe, os.spawnv, os.spawnve,
    os.spawnvp, os.spawnvpe, os.startfile]
  shell: [os.system, os.popen, os.popen2, os.popen3, os.popen4, popen2.popen2, popen2.popen3,
    popen2.popen4, popen2.Popen3, popen2.Popen4, commands.getoutput, commands.getstatusoutput]
  subprocess: [subprocess.Popen, subprocess.call, subprocess.check_call, subprocess.check_output,
    subprocess.run]

# Make sure we get proper output format for CI
output_file: bandit-output.json
output_format: json
