name: Backend CI

on:
  push:
    branches: [ main ]
    paths:
      - 'backend/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'backend/**'

jobs:
  test-and-lint:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'pip'
    
    - name: Install dependencies
      working-directory: ./backend
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest pytest-cov mypy types-sqlalchemy bandit
        pip install -r requirements.txt
    
    - name: Lint with flake8
      working-directory: ./backend
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
        
    - name: Type check with MyPy
      working-directory: ./backend
      run: |
        mypy --ignore-missing-imports --disallow-untyped-defs --disallow-incomplete-defs --check-untyped-defs models schemas routes
        
    - name: Security scan with Bandit
      working-directory: ./backend
      run: |
        bandit -r . -x ./tests,./venv -f json -o bandit-results.json || true
        bandit -r . -x ./tests,./venv --severity-level medium -f screen
    
    # We'll create a basic test directory and setup file if none exists
    - name: Setup test directory if it doesn't exist
      run: |
        if [ ! -d "backend/tests" ]; then
          mkdir -p backend/tests
          touch backend/tests/__init__.py
          echo "import pytest
          def test_placeholder():
              assert True" > backend/tests/test_placeholder.py
        fi
    
    - name: Test with pytest
      working-directory: ./backend
      run: |
        pytest --cov=. --cov-report=xml
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./backend/coverage.xml
        fail_ci_if_error: false
